### ISSUE TITLE
ERROR: Target media "/dev/sda1" is not an entire storage device!

### ISSUE THREAD

**Issue by ghost** [WoeUSB/WoeUSB#103]
## Describe the bug ##

I want to flash windows 10 iso to my usb

## To Reproduce ##

run command 
 ```sh 
sudo ./woe.bash -d ./win.iso /dev/sda1
 ```

## Teminal output ##

![img](https://user-images.githubusercontent.com/98218366/172767626-307e391d-2f63-4939-a7f7-39edaf4c888f.png)

```your-woeusb-output-here:
ERROR: Target media "/dev/sda1" is not an entire storage device!
WoeUSB 5.2.4 Help Information
=============================
```
## Environment ##

- OS: [e.g. Ubuntu] Ubuntu 22.04 LTS
- Bash: [e.g. `bash --version`] 5.1.16(1)-release
- WoeUSB: [e.g. 5.0.1] 5.2.4

**Comment by ghost** [comment]
I have formatted it in a ntfs system and created a blank partition
![immagine](https://user-images.githubusercontent.com/98218366/172769537-00862ba2-1762-4155-905e-26c563e26a9c.png)

**Comment by brlin-tw** [comment]
Please use the full storage device node (`/dev/sda`) as the command-line argument.  Also, note that in the `--device` preparation mode the partition table will be cleared thus the original partition(s) will no longer exist.

**Comment by kenail2002** [comment]
> Please use the full storage device node (`/dev/sda`) as the command-line argument. Also, note that in the `--device` preparation mode the partition table will be cleared thus the original partition(s) will no longer exist.

right
