### ISSUE TITLE
Does the last 3% take an eternity or what?

### ISSUE THREAD

**Issue by Stapleton** [WoeUSB/WoeUSB#13]
Apologies for the bad formatting of an "issue", this is more of a "Is this actually supposed to be a thing or no?". Just frustrated, 4 days trying to make a windows USB and nothing is working thus far.

System NeoFetch https://i.imgur.com/rGeGF83.png
Using WoeUSB version `4.0.3`
Image: `Win10_20H2_English_x64.iso`
Device Mode: `/dev/sdd`, 16GB USB Flash Drive
CLI Args: `--tgt-fs NTFS --workaround-bios-boot-flag --device ~/Downloads/Win10_20H2_English_x64.iso /dev/sdd`
Console Log at the time of writing this: https://pastebin.com/SY5hSFt6

Its been hung on 97% for over 30 minutes at this point. Is this expected behaviour?

**Comment by Lin-Buo-Ren** [comment]
It is expected to encounter a long duration during the preparation of an NTFS based drive due to the poor I/O performance of the regular-priced USB keys, please allow 1~2 hour of time before bailing out.

**Comment by Stapleton** [comment]
Alright, awesome! Thank you for the response! That actually helps a lot
