### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [WoeUSB/WoeUSB#130]
## Is your feature request related to a problem? Please describe ##

1. I want to create a windows bootable image.
2. I do not want to read the documentation for every dependency on how to install it.

## Describe the solution you'd like ##

Install the required dependencies when running `woeusb-X.Y.Z.bash`.

## Describe alternatives you've considered ##

Add the instructions to copy and paste to install the dependencies.

## Additional context ##

NA

**Comment by brlin-tw** [comment]
While we understand the convenience of implementing the dependency installation logic directly in WoeUSB, the variety of distributions, distribution versions, and dependency availability in each of these versions would make the application too complex to maintain and is thus determined to be out-of-scope of this project.

We recommend referring to the existing [Dependencies documentation](https://github.com/WoeUSB/WoeUSB#dependencies) and [the wiki article](https://github.com/WoeUSB/WoeUSB/wiki/Dependencies) for assistance on installing the dependencies to run WoeUSB.
