### ISSUE TITLE
Why is the install.<esd|wim> being modified to a .swm?

### ISSUE THREAD

**Issue by JW0914** [WoeUSB/WoeUSB#136]

**Comment by brlin-tw** [comment]
Here's the last(2024-08-15T13:19:24Z) available issue body published by @JW0914, for everyone's convenience:

>I’m a bit baffled why this script is modifying the `install.<esd|wim>` to a read-only split WIM \[`.swm`\], which it literally has no business touching, as the only thing that needs to be done is a USB drive needs to be made bootable, and the ISO _extracted_ to the USB drive _**untouched**_.
>
>* Split WIMs aren’t even used in the correct way - they’re obsolete to begin with, and their _sole_ purpose is for laptop/PC OEMs to apply their bloatware over the default base file system contained within an `install.<esd|wim>` during the ZTI Task Sequence
>
>**What changes is the script making to the default OS file system contained within the `install.<esd|wim>`?**
>
>Simply put, this script isn’t able to be trusted because **there is _no use case_ for modifying the base Windows file system** for 99% of users, and since there is no use case for doing so, this by default implies a nefarious purpose; even more so when the user receives no info regarding this, nor an ability to reject the modification.
>
>* The only way to go around this is to manually delete the modified `install.<esd|wim>`, copying back over the untouched one from the ISO
> 
> I can see only two reasons why this is being done since no use case exists for it, either:
> 
>* developers have no understanding of what they’re doing
> * Malware is being injected into the base default Windows file system, which would be hard to detect
>
>Seriously, what are you folks thinking? You don’t modify the default _trusted_ file system of an OS contained within an installer.

**Comment by JW0914** [comment]
I intentionally cleared the message body, as while the script states this is due to maintain an <4GB file, there should be no reason to split an ESD
  - Exporting _any_ ESD/WIM index of an `install.<esd|wim>` to an ESD will almost _always_ create an ESD that’s <4GB _(it’s the norm, not the exception)_, as the ESD compression algorithm is 33% more efficient than WIM’s

**The way this script does this is highly inefficient and _not required_.**
  - It’s a really bad idea all around because users aren’t made aware, nor is it explicitly stated what’s going on, and it provides the _potential_ for malware to be injected into the default Windows file system prior to install should this developer account become compromised _(this isn’t possible with the default `install.<esd|wim>` since you can’t commit changes to either)_

It serves everyone’s best interest for the steps to export to a SWM to be completely removed from the script:
  - All that needs to be done on Linux to create a Windows Install USB is to create the correct partition table _(BIOS: MBR | UEFI: GPT)_, for the partition to be marked bootable if BIOS, and for the ISO to be _extracted **as-is**_ to the USB drive _(that’s literally it)_
  
The way this script currently works creates a trust deficit
