### ISSUE TITLE
Add Fedora dependency instructions

### ISSUE THREAD

**Issue by jones77** [WoeUSB/WoeUSB#137]
## Is your feature request related to a problem? Please describe ##

Add the following install instructions for Fedora to the install Wiki page.  (lmk If I can enter a regular PR and I'll do so, but I didn't really know how (or if it's possible) to submit a PR for a wiki?)

## Describe the solution you'd like ##

    $ sudo dnf install bash dosfstools findutils grep gawk grub2-common grub2-pc ntfs-3g p7zip

## Additional context ##

I used `dnf search` to find best matches and looks like the bash script is working now.

**Comment by brlin-tw** [comment]
@jones77 Thanks for your report!  I believe anyone registered on GitHub can directly edit the wiki pages, can you first try it out?

**Comment by brlin-tw** [comment]
@jones77 I have rectified an configuration error that prevent non-organization members to edit the wiki pages, please check whether there's an Edit button in the wiki, as depicted in the following screenshot:

![Screenshot](https://github.com/user-attachments/assets/42f4460d-54c5-4a43-8caf-8ecadf35f932)

Thanks!

**Comment by rathann** [comment]
Is it really necessary, though? WoeUSB is present in Fedora repositories, so you're actually better off running `dnf install WoeUSB`.

**Comment by brlin-tw** [comment]
@rathann

> WoeUSB is present in Fedora repositories, so you're actually better off running `dnf install WoeUSB`.

It'll be helpful for people who want to run from source for whatever reason, IMHO it's a nice addition.

**Comment by jones77** [comment]
Done! https://github.com/WoeUSB/WoeUSB/wiki/Dependencies#fedora

Also, thanks @rathann &mdash; that never occurred to me 🙃.
