### ISSUE TITLE
Is this now the active project? (And issue migration?)

### ISSUE THREAD

**Issue by max-rosenfors** [WoeUSB/WoeUSB#2]
## Active project

I was browsing around reading about the write issues regarding NTFS formatted partitions required for Win10-isos on the [other project page](https://github.com/slacka/WoeUSB), and I wondered a bit about the status of the project in general.

Mentioned over here by Lin-Buo-Ren this is supposed to be a new active project: https://github.com/slacka/WoeUSB/issues/209#issuecomment-699851697

## Issue migration/priority

Also, as far as I can imagine due to the state of Win7 being more or less abandoned my MS, I imagine the main usage of WoeUSB should be for creating Win10 boot sticks. I'm currently writing a stick myself with the latest ISO from MS which requires me to use NTFS because of the >4GB files which wont fit on a FAT32 partition. I've set a timer for good measure, it has been stuck on the "Installing for i386-pc platform." for just over 21 minutes as of writing. (If I remember I'll get back here with a comment of the total time taken once it is finished)

Not sure if there are more critical issues regarding the project available currently, for my use on Ubuntu 20.04 this was the only hurdle from it being a near perfect alternative for me to something like Rufus on Linux.

Here are two old issues talking about what seems to be the same problem (which also contain important discussions about the underlying cause):
- [Prepare installation device with NTFS as target filesystem took too long #247](https://github.com/slacka/WoeUSB/issues/247)
- [woeusb hangs on 'install-grub' step #251](https://github.com/slacka/WoeUSB/issues/251)

**Comment by Lin-Buo-Ren** [comment]
Yes, this will be a valid project start from 2020/10/10 0:00:00 UTC+8, the migration has been started but not online yet.

For the "Installting for i386-pc platform" time issue, there's an existing patch that should deal with, however it requires review before merging, which should be done in the near future.

**Comment by max-rosenfors** [comment]
Great!

*The installation just finished on my side clocking in at 1h 17m.*
