### ISSUE TITLE
read iso file from stdin

### ISSUE THREAD

**Issue by jrabinow** [WoeUSB/WoeUSB#20]
## Is your feature request related to a problem? Please describe ##
No hard drive space to save iso file to disk - the script must read the iso from a file saved to disk

A clear and concise description of what the problem is.
Windows ISOs tend to be large. On old hardware or in some situations (for example liveusb), this can limit situations where this script can be used if the iso is too large to hold on disk.

## Describe the solution you'd like ##
Allow woeusb to read the iso file from stdin instead of requiring it to be read from a file

1/ Download windows iso on laptop 1, currently not running linux.
2/ Transfer windows iso to laptop 2 with hardware restrictions. Use ncat or ssh, both of which will spit out the file contents to stdout by default. Or download the iso file directly to laptop 2 with `curl` if that's an option.
3/ Pipe the ncat/ssh/curl output from 2/ into woeusb, running in "read iso from stdin mode"

This would enable writing data to usb without it ever having to be persisted to disk, similar to what can be done with `dd` command: `cat foobarfile | dd of=myoutputfile`
The final setup could be used like this:
Laptop 1:
`ncat -vw1 $LAPTOP_2_IP_ADDR $PORTNO < windows.iso`
Laptop 2:
`ncat -w1 -vlp $PORTNO | pv | sudo ./woeusb --device - /dev/sdX`

## Describe alternatives you've considered ##
Use tmpfs https://www.kernel.org/doc/html/latest/filesystems/tmpfs.html

Create tmpfs with `mkdir /mnt/tmpfs; mount -t tmpfs none /mnt/tmpfs`
Download iso file into tmpfs
Run the script as usual
Potential issue with this case: if ram gets saturated, the OS can crash or the download can fail
Second workaround: get different hardware

## Additional context ##
Thank you so much for this project, it's truly a lifesaver

**Comment by Lin-Buo-Ren** [comment]
This is an interesting proposal, however, I wonder why you can't simply run a WoeUSB-like application right on _laptop 1_.

In practice implementing this is not going to be easy as the image(stdin) needs to be mounted on the _laptop 2_, which, as far as I concerned, not possible.

**Comment by jrabinow** [comment]
In my specific case, laptop 1 is running mac os x which has gotten locked down more and more over the years, to the point where none of the tools I'm aware of (bootcamp assistant, unetbootin, raw `dd` command, balenaEtcher) seem to work anymore. I used the tmpfs workaround listed above to solve my issue.

I was hoping that creating windows ISOs was possible with `dd`, same as linux, in which case no need to mount anything. But if the ISO requires mounting for windows, indeed I don't think this is possible without an insane amount of work 😞

Thanks again for your work on this tool!

**Comment by Lin-Buo-Ren** [comment]
Is it possible to run an SSH/FTP service on your Mac OS X, and mount it remotely in _laptop 2_ via sshfs/CurlFtpFS?  WoeUSB should work in this way.

**Comment by jrabinow** [comment]
Any and all connections to the mac host, including ping, seem to be blocked by the built-in firewall - I'm sure I could fiddle with it and get it working, but given that the tmpfs workaround went through, I'll keep networked file systems in mind for next time.
I should have thought of those, they would definitely have solved the problem on my end. Good suggestion :-)

**Comment by jrabinow** [comment]
Not sure if I should close this issue or not, will leave it up to you

**Comment by Lin-Buo-Ren** [comment]
Thanks for your consideration, until it is proven technically possible I'll close this for now.
