### ISSUE TITLE
Please help (DISK NOT SHOWING IN WOEUSB)

### ISSUE THREAD

**Issue by ChargingJoe** [WoeUSB/WoeUSB#21]
Hi . I'm trying to use woeusb but my pendrive/Disk is not showing up
i have ensured that i have mounted my usb 
![WOEUSB](https://user-images.githubusercontent.com/71560927/99414099-7beec200-291c-11eb-9cdb-37a93bad8306.png)

**Comment by Lin-Buo-Ren** [comment]
The GUI wrapper application is no longer the scope of this project, please file the issue to <https://github.com/WoeUSB/WoeUSB-frontend-wxgtk/issues> instead.  Note that it is currently unmaintained and will not likely be supported in the near future.

As an alternative, you may want to use the core `woeusb` program, refer <https://github.com/WoeUSB/WoeUSB#run-from-source> for more info.
