### ISSUE TITLE
allow fit multiple ISO-files in one USB-storage device

### ISSUE THREAD

**Issue by edmundlaugasson** [WoeUSB/WoeUSB#23]
## Is your feature request related to a problem? Please describe ##

The problem is, that you never know, whether the target system is 64-bit or 32-bit capable. Also if there is less memory, there might be 32-bit more reasonable.
Another issue is, if there are multiple languages, then for each language is separate USB-stick needed to create. I propose to allow them to be on one USB-stick. Today USB-sticks have lots of space, there could be easily fit more than one onto one USB-stick. Also it is not easy to update such USB-stick - it requires lots of time. If something goes wrong, it starts over.

## Describe the solution you'd like ##

`woeusb --device-multi iso-1.iso iso-2.iso .... iso-n.iso /dev/sdX`

Or there could be just same command but with more than one ISO-file support:
`woeusb --device iso-1.iso iso-2.iso .... iso-n.iso /dev/sdX`
... if it is possible to do so. If not, then separate parameter for multiple ISOs can be created.

There should be menu available to choose between 32-bit, 64-bit and different languages. There could be just every ISO-file listed in the menu - would be sufficient, e.g.:
- Win10_20H2_English_x32
- Win10_20H2_English_x64
- Win10_20H2_Estonian_x32
- Win10_20H2_Estonian_x64

These would be ~19,5 GB - there are 32 GB USB-sticks available, which are quite common nowadays. Also much larger are available. Even external SSD could be used, which volumes are in terabytes. **In such case (SSD used), the search by type would be useful, because the menu can be very long due to lots of items of ISO-files - there should be a search line, where can type.** Starting typing will automatically filter available items in menu. Such searching by typing should work in case of any part of menu item. E.g. starting typing language name will also work, even the language name is part of the filename and not necessarily the first word in menu.

**I guess automatically creating menu would be enough.** No need to create parameter for that. If there is one ISO in determined folder, then no menu will be generated. If there is more than one ISO, automatically menu will be generated.

**Would be even more easier, if there could be also easily updated such USB-stick**, when new versions of MS Windows 10 comes out twice per year. The easiest way could be just copy ISO-files onto USB-stick, e.g. to determined folder and that's it. When booting such USB-stick, then WoeUSB would automatically identify *.iso files in specific folder on USB-stick and creates appropriate boot menu, if more than one ISO-file have been found. Then mounts selected ISO over loopback and rest of boot process goes like it used to. Using ISO-files will not mix its contents on USB-stick and therefore they can co-exist and used.
In case of new MS Windows 10 version, we just download new ISO-files, after checking checksums, delete old ISO-files from USB-stick and copy new ones. Also, if would like to add other Windows versions, just copy additional ISO files to that determined folder and on next boot these fill be recognized.

## Describe alternatives you've considered ##

Microsoft has Media Creation Tool (MCT). Using it under MS Windows it is possible to put 32-bit and 64-bit onto one USB-stick if there is MS Windows PC available. Or try to use Wine under Linux to run that MCT under Linux.

## Additional context ##

When just copying ISO-files, then it would be much more easier to prepare USB-storage. Although I'm not sure, whether MS Windows allows to do so.

**Comment by JonnyTech** [comment]
@edmundlaugasson what you are suggesting is adding complication to the simple nature of [WoeUSB](https://github.com/WoeUSB/WoeUSB).

I suggest to use a dedicated tool such as [Ventoy](https://github.com/ventoy/Ventoy) instead.

**Comment by edmundlaugasson** [comment]
Thanks for hint, will try. If WoeUSB needs to be simple, then let it be.

**Comment by Lin-Buo-Ren** [comment]
We boot Windows installation via chain-loading Microsoft's bootloader, which has unknown behavior if we change the directory structure to attempt to support multiple ISOs.  Better use an alternative that specifically supports it.
