### ISSUE TITLE
automatically asking proper superuser if forgot to use

### ISSUE THREAD

**Issue by edmundlaugasson** [WoeUSB/WoeUSB#26]
## Is your feature request related to a problem? Please describe ##

Currently if you forgot to use sudo prior WoeUSB command, you will get bunch of error messages. It takes some time to find out relevant lines from that long text in order to understand, that you just forgot sudo before the woeusb command

## Describe the solution you'd like ##

In case of running woeusb without sudo, it should automatically ask your user password and run it via sudo. If the current user is not the member of sudo group, WoeUSB should ask that user username and password, who has sudo in current PC.
In case of non-sudo Linux distro, it should ask root user and its password.

## Describe alternatives you've considered ##

Currently just manually is needed to determine the use of superuser permissions and use sudo command or switch to root via **su - root** command

## Additional context ##

It makes the use of WoeUSB much more smooth to behave appropriately in case the user forgot to use the superuser power.

**Comment by brlin-tw** [comment]
First of all, apologies for the ignorance.

This feature is really nice to have, however, there are several reasons I believe that this is not preferable to be implemented:

* Logic must be implemented to determine which permission elevation method the user is able to use (su/sudo/Polkit/...)
* The `sudo` group for users that can run arbitrary commands via sudo does not portable (only available in Debian-ish distros), guessing all the distro-group combination also increases the code complexity
* There are circumstances that a user _may_ be able to run WoeUSB even when it doesn't have superuser privileges, like in certain containerized distributions where necessary access is provided via "magic" of each solution, detect these special cases also increases code complexity

Currently, WoeUSB gives a warning in the early stage when a user seems to have no access to the devices, which should be enough to alert the user something's going wrong:

![Current message output screenshot when running WoeUSB as a regular user](https://user-images.githubusercontent.com/13408130/141697220-8eb2cdef-dfcb-4f15-a8b1-6761e25c5f12.png "Current message output when run WoeUSB as a regular user")

The application also bails out early when an error has occurred so I believe there should be less issue for one to notice the cause of the failure.
