### ISSUE TITLE
line 2063: script_name: unbound variable

### ISSUE THREAD

**Issue by techana** [WoeUSB/WoeUSB#28]
## Describe the bug ##

When trying to run woeusb-5.0.4.bash , the following error is given:

```
./woeusb-5.0.4.bash: line 2063: script_name: unbound variable
```

## Environment ##

- OS: centOS 7
- Bash: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
- WoeUSB: 5.0.4

**Comment by Lin-Buo-Ren** [comment]
WoeUSB [only supports Bash >=4.3](https://github.com/WoeUSB/WoeUSB#dependencies), which is not shipped by CentOS 7, please upgrade your bash installation and retry.
