### ISSUE TITLE
Add step-by-step how to install on Ubuntu 

### ISSUE THREAD

**Issue by ericoporto** [WoeUSB/WoeUSB#30]
The README states the dependencies, but it would be helpful to have a `sudo apt install DEPENDENCIES` command to ctrl+c and ctrl+v for the installation of them. Or at least have the packages listed with the names they have in the distro.

Also it says "Run from source" but the step by step instructions need archives from the Release page and not git clone from the repository source, which is unhelpful for running from the source for development.

**Comment by Iscrimou** [comment]
We need to be expert in linux to install this

**Comment by Lin-Buo-Ren** [comment]
Apologies for the ignorance.  We've made distro-specific installation instructions available in the wiki(which is referenced by the project README), does that work for you?

We would like to keep the upstream source clean from the distro-specific details(as we certainly can't maintain all of them), while at the same time allow the community to help themselves.

**Comment by ericoporto** [comment]
I still don't understand why run from source doesn't use git clone. Is there anything else that is not in the repo for some reason but is on the release? People could checkout tags of stable version if the main branch doesn't always build.

Bonus, no need to change permissions: https://git-scm.com/docs/git-update-index#Documentation/git-update-index.txt---chmod-x

> Apologies for the ignorance. We've made distro-specific installation instructions available in the wiki(which is referenced by the project README), does that work for you?

I see now, I still find it's a bit too cryptic and could be better explained in the README. If you add in the README people from other distros could contribute through PRs. If you don't, then it needs to be clearly written, anyone's eyes will scan the README looking for the `apt`, `aur`, `yum`, `emerge`, ...

Anyway, at the time all my Windows PCs had died and I was looking for how to build a pen drive but I have since solved things. Feel free to close this issue.
