### ISSUE TITLE
Do I need to be a Linux expert to use this?

### ISSUE THREAD

**Issue by RenanRischiotto** [WoeUSB/WoeUSB#32]
...

**Comment by Iscrimou** [comment]
Yes, we need. I don't understand anything here

**Comment by mirsella** [comment]
don't worry it's simple.
with `lsblk` you can see all your device, get your USB device probably something like sd + a letter of the alphabet. get the right one or you will erase the wrong disk. for example here we will say it's sdd.

then `woeusb -d "path of the iso" /dev/sdd` and it's done. 

i encountered 2 kind of error :

1) my desktop environment (kde, gnome, etc) would auto matically mount the USB device which prevent woeusb from doing it's work. you need to un mount the USB device, `sudo umount /dev/sdd` to umount the device,
and then depending on the desktop environment temporarily disable the auto mount of the device. on kde you can do 
- right click the USB key icon in the task bar, and click on configure removable devices
- in the settings go to removable storage
then un tick the main case  "enable automatic mounting of removable media." and click apply. you can re tick it after using woeusb

2) the error ```
Error: File "/tmp/woeusb-source-20210124-111815-Sunday.80mace/sources/install.wim" in source image has exceed the FAT32 Filesystem 4GiB Single File Size Limitation and cannot be installed.  You must specify a different --target-filesystem.                               
Refer: https://github.com/WoeUSB/WoeUSB/wiki/Limitations#fat32-filesystem-4gib-single-file-size-limitation for more info.
```
which is well explained as there is a link with exactly what to do. you need to add ` --target-filesystem NTFS` to the command.

i hope this helped, you see it wasn't that hard.

**Comment by Lin-Buo-Ren** [comment]
Apologies for the ignorance, unfortunately the Wxwidget GUI wrapper has to be dropped due to lack of maintenance expertise.  If the problem is mitigated we surely can make it available again.

As of now I would like to focus on fixing the papercuts in the CLI program to be as easy to use as possible.

If you really need GUI please check out @WoeUSB/WoeUSB-ng which does provide one.
