### ISSUE TITLE
sorrry, app not working :-(

### ISSUE THREAD

**Issue by welon68** [WoeUSB/WoeUSB#34]
[welon@wel windows10]$ 
[welon@wel windows10]$ sudo woeusb --device Win10_1803_Polish_x64.iso /dev/sdf --target-filesystem NTFS
[sudo] hasło użytkownika welon: 
WoeUSB v5.0.4
==============================
Mounting source filesystem...
Wiping all existing partition table and filesystem signatures in /dev/sdf...
/dev/sdf: usunięto 2 bajty pod offsetem 0x000001fe (dos): 55 aa
/dev/sdf: wywoływanie ioctl w celu ponownego odczytu tablicy partycji: Sukces
Ensure that /dev/sdf is really wiped...
Creating new partition table on /dev/sdf...
Creating target partition...
Making system realize that partition table has changed...
Wait 3 seconds for block device nodes to populate...
Cluster size has been automatically set to 4096 bytes.
Creating NTFS volume structures.
Failed to sync device /dev/sdf1: Błąd wejścia/wyjścia
Syncing device. FAILEDThe command ""${command_mkntfs}" --quick --label "${filesystem_label}" "${target_partition}"" failed with exit status "1", program is prematurely aborted
Unmounting and removing "/tmp/woeusb-source-20210203-122941-Wednesday.a6ntJC"...
Unmounting and removing "/tmp/woeusb-target-20210203-122941-Wednesday.edRtte"...
umount: /tmp/woeusb-target-20210203-122941-Wednesday.edRtte: nie zamontowany.
cleanup_mountpoint: Warning: Unable to unmount "/tmp/woeusb-target-20210203-122941-Wednesday.edRtte".
Some mountpoints are not unmount/cleaned successfully and must be done manually
You may now safely detach the target device
[welon@wel windows10]$ ^C
[welon@wel windows10]$

**Comment by WaxyMocha** [comment]
Seems like your target device is broken, can you try with other usb stick?

**Comment by Lin-Buo-Ren** [comment]
Apologies for the ignorance.  As what @WaxyMocha has mentioned the target device seems to be faulty, please try again on a different drive.
