### ISSUE TITLE
The following packages have unmet dependencies:  woeusb : Depends: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) but it is not installable E: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by shahidkarimi** [WoeUSB/WoeUSB#37]
The following packages have unmet dependencies:
 woeusb : Depends: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by Lin-Buo-Ren** [comment]
Please refer to the proper issue tracker: <https://github.com/WoeUSB/WoeUSB-frontend-wxgtk/issues>
