### ISSUE TITLE
Requires wimlib-imagex, but has installed on Debian

### ISSUE THREAD

**Issue by moabson** [WoeUSB/WoeUSB#44]
This error occurs on run **woeusb-5.1.0.bash**, 

`check_runtime_dependencies: Error: WoeUSB requires wimlib-imagex command in the executable search path, but it is not found.`

Screenshot shows the **wimlib-imagex** has been installed.

![Captura de tela de 2021-03-21 17-59-42](https://user-images.githubusercontent.com/2575708/111920746-74c4f580-8a6f-11eb-8940-af2139433040.png)

**Comment by Lin-Buo-Ren** [comment]
Try installing the `wimtools` package, which should ship the required commands

**Comment by moabson** [comment]
> Try installing the `wimtools` package, which should ship the required command.

Works fine after installation of `wimtools` but i needed to install `grub-pc-bin` after. Already exists an Installation Guide? if not, need to consider making it.

**Comment by Lin-Buo-Ren** [comment]
We currently host the distribution-specific dependency details in the wiki, as of now only Ubuntu is documented.

I'll add a hint in the README to make clear what component is exactly needed for the wimlib dependency, though.

**Comment by moabson** [comment]
Thanks!
