### ISSUE TITLE
Does it sudo? Also it wants to unmout sources not mounted?

### ISSUE THREAD

**Issue by chemicalvamp** [WoeUSB/WoeUSB#67]
## Describe the bug ##
I'm getting access denied, and no prompt for a password.

## To Reproduce ##
Just follow the terminal output

## Expected behavior ##
I would think it would ask for a password and then do the permission needing work.

## Teminal output ##
keith@keith-HP-x2-Detachable:~$ sudo woeusb --device </home/keith/Downloads/Win10_21H1_English_x64.iso> /dev/sda --target-filesystem ntfs
bash: /dev/sda: Permission denied

## Trying harder ##
keith@keith-HP-x2-Detachable:~$ sudo bash
[sudo] password for keith: 
root@keith-HP-x2-Detachable:/home/keith# woeusb --target-filesystem NTFS --device </home/keith/Downloads/Win10_21H1_English_x64.iso> /dev/sda
ERROR: --umount: /tmp/woeusb-source-20210523-201807-Sunday.7LfgKQ: not mounted.
Warning: Unable to unmount "/tmp/woeusb-source-20210523-201807-Sunday.7LfgKQ".
umount: /tmp/woeusb-target-20210523-201807-Sunday.D6iU8H: not mounted.
Warning: Unable to unmount "/tmp/woeusb-target-20210523-201807-Sunday.D6iU8H".
Warning: Some mountpoints are not unmount/cleaned successfully and must be done manually
root@keith-HP-x2-Detachable:/home/keith# umount /tmp/woeusb-source-20210523-201807-Sunday.7LfgKQ
umount: /tmp/woeusb-source-20210523-201807-Sunday.7LfgKQ: not mounted.

## Environment ##
- OS: [Ubuntu 20.04.2 LTS]
- Bash: [GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)]
- WoeUSB: [WoeUSB @@WOEUSB_VERSION@@ Help Information] is all i see, it was the latest as of today whatever that may be.

## Additional context ##
I was following https://www.linuxuprising.com/2020/10/how-to-make-bootable-windows-10-usb-on.html
and this guide is broken as well, for me if --target-filesystem NTFS comes at the end as they say it doesnt work.

Also i had to add a dependency manually wimtools iirc
woeusb : Depends: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) but it is not installable

**Comment by Lin-Buo-Ren** [comment]
> keith@keith-HP-x2-Detachable:~$ sudo woeusb --device </home/keith/Downloads/Win10_21H1_English_x64.iso> /dev/sda --target-filesystem ntfs

The angle brackets displayed in the `--help` message are a placeholder marker, and shouldn't be added in the actual command.

**Comment by chemicalvamp** [comment]
Yes i thought so too the first time, But the order of --device and then --filesystem-type caused an error. Removing the <> was the first thing i did in my many attempts to get it to work, of coarse they ended up back because absolutely nothing was working.

I blame the guide mostly. but i spent way too much time troubleshooting this. I used bootiso maybe you can have a look at how they auto install dependencies. Finally get yours in order. And get the exception worked out because permission denied and nothing else doesnt look like syntax error one bit.
