### ISSUE TITLE
We should really pin the UEFI:NTFS version

### ISSUE THREAD

**Issue by brlin-tw** [WoeUSB/WoeUSB#7]
To avoid problems like image size changes breaking drive preparation.

**Comment by Lin-Buo-Ren** [comment]
Unfortunately [UEFI:NTFS isn't tagging any releases](https://github.com/pbatard/uefi-ntfs/releases)...so our best bet is to pin [the one used in Rufus instead](https://github.com/pbatard/rufus/releases)

**Comment by tukusejssirs** [comment]
> Unfortunately [UEFI:NTFS isn't tagging any releases](https://github.com/pbatard/uefi-ntfs/releases)...so our best bet is to pin [the one used in Rufus instead](https://github.com/pbatard/rufus/releases)

Or we could simply pin the version down by commit hashes, potentially in a submodule. :wink:

**Comment by brlin-tw** [comment]
The UEFI:NTFS filesystem image version is now pinned via specifying the commit hash in the download URL, for pinning via submodule the issue is tracked in #85
