### ISSUE TITLE
ERROR: WoeUSB requires wimlib-imagex command in the executable search path, but it is not found.

### ISSUE THREAD

**Issue by Mr-M1M3** [WoeUSB/WoeUSB#71]
When I try to execute, 

`sudo ./path/to/woeusb.bash`

I get following error:

```
ERROR: WoeUSB requires wimlib-imagex command in the executable search path, but it is not found.

Info: Unmounting and removing "/tmp/woeusb-source-20210623-095116-Wednesday.1lPnhT"...
umount: /tmp/woeusb-source-20210623-095116-Wednesday.1lPnhT: not mounted.
Warning: Unable to unmount "/tmp/woeusb-source-20210623-095116-Wednesday.1lPnhT".
Info: Unmounting and removing "/tmp/woeusb-target-20210623-095116-Wednesday.lQI6er"...
umount: /tmp/woeusb-target-20210623-095116-Wednesday.lQI6er: not mounted.
Warning: Unable to unmount "/tmp/woeusb-target-20210623-095116-Wednesday.lQI6er".
Warning: Some mountpoints are not unmount/cleaned successfully and must be done manually
```

**Comment by Lin-Buo-Ren** [comment]
WoeUSB [now requires a wimlib installation](https://github.com/WoeUSB/WoeUSB#dependencies), please install it and try again.

**Comment by ElSebita** [comment]
I get this error:
`wimlib-imagex: error while loading shared libraries: libwim.so.15: cannot open shared object file: No such file or directory`
And waits forever. Doing CTRL+C to quit throws this error:
`Warning: Recieved SIGINT, program is interrupted.
ERROR: The command "sleep 1" failed with exit status "1", program is prematurely aborted`

**Comment by CRImier** [comment]
On Ubuntu, `apt install wimtools` seems to do the trick.
