### ISSUE TITLE
Unsupported oversized file, Windows could not collect information for [OSImage]

### ISSUE THREAD

**Issue by DavutHaxor** [WoeUSB/WoeUSB#78]
I am getting `Warning: Unsupported oversized file "./sources/install.esd" detected, this file will NOT be transferred` while installing windows iso.

My WoeUSB output:
```
sudo woeusb -d /home/davut/Downloads/AME20H2.iso /dev/sdb                                                                                             1 ✘ 
WoeUSB v5.1.2
==============================
Info: Mounting source filesystem...
Info: Wiping all existing partition table and filesystem signatures in /dev/sdb...
/dev/sdb: 2 bytes were erased at offset 0x000001fe (dos): 55 aa
/dev/sdb: calling ioctl to re-read partition table: Success
Info: Ensure that /dev/sdb is really wiped...
Info: Creating new partition table on /dev/sdb...
Info: Creating target partition...Info: Making system realize that partition table has changed...blockdev: ioctl error on BLKRRPART: Device or resource busy
Info: Wait 3 seconds for block device nodes to populate...mkfs.fat 4.2 (2021-01-31)
mkfs.fat: Warning: lowercase labels might not work properly on some systems
Info: Mounting target filesystem...
Info: Copying files from source media...
Warning: Unsupported oversized file "./sources/install.esd" detected, this file will NOT be transferred.
Info: Installing GRUB bootloader for legacy PC booting support...
Installing for i386-pc platform.
Installation finished. No error reported.
Info: Installing custom GRUB config for legacy PC booting...
Info: Done :)
Info: The target device should be bootable now
Info: Unmounting and removing "/tmp/woeusb-source-20210924-195613-Friday.YB4xTr"...
Info: Unmounting and removing "/tmp/woeusb-target-20210924-195613-Friday.7Vv7xf"...
Info: You may now safely detach the target device
```

- OS: Manjaro KDE
- Bash: GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
- WoeUSB: 5.1.2

Also when i try to click "Install" after i boot the UEFI, it gives the error: `Windows could not collect information for [OSImage] since the specified image file [install.wim] does not exist.`

**Comment by JonnyTech** [comment]
With recent versions of windows you need to use the NTFS option when running woeusb.

**Comment by Lin-Buo-Ren** [comment]
> Warning: Unsupported oversized file "./sources/install.esd" detected, this file will NOT be transferred.

Currently, the ESD format of the install image isn't supported, if it isn't really encrypted and can be properly dealt with by the wimtools it may be possible for WoeUSB to support them.

**Comment by Lin-Buo-Ren** [comment]
NOTE: 

> wimlib can also be used to handle ESD (Electronic Software Download) (.esd) archives in addition to WIM (.wim) archives. ESD archives are WIM archives that use solid-mode LZMS compression, and so usually have a significantly smaller size than regular WIM archives. However, Microsoft sometimes distributes ESD archives in (partially) encrypted form. wimlib cannot decrypt such archives by itself. 

Source: [wimlib - Main page](https://wimlib.net/)

**Comment by DavutHaxor** [comment]
Outdated issue.
