### ISSUE TITLE
Cannot write uefi-ntfs.img to uefi partition

### ISSUE THREAD

**Issue by kamuridesu** [WoeUSB/WoeUSB#82]
## Describe the bug ##

Cannot write uefi-ntfs.img to uefi partition, not enough space. The USB stick has 14,9G, more than enough, but the UEFI partition is created with only 512k. As the image `uefi-ntfs.img` has ~1M, it gives this error.

## To Reproduce ##

1. `sudo ./woeusb-5.1.2.bash --device ~/Downloads/Win10_21H1_BrazilianPortuguese_x64.iso /dev/sdb --tgt-fs NTFS`
2. See error

## Expected behavior ##
Bootable device to be created

## Teminal output ##
```
2021-10-30 09:57:57 (2,84 MB/s) - “/tmp/WoeUSB.tempdir.NGByCR/uefi-ntfs.img” saved [1048576/1048576]

dd: writing in '/dev/sdb2': Not enough space on device
1025+0 registros de entrada
1024+0 registros de saída
524288 bytes (524 kB, 512 KiB) copiados, 0,122135 s, 4,3 MB/s
ERROR: The command "dd if="${download_directory}/uefi-ntfs.img" of="${uefi_ntfs_partition}"" failed with exit status "1", program is prematurely aborted
```

## Environment ##

- OS: Arch Linux
- Bash: 5.1.8(1)-release
- WoeUSB: 5.1.2

**Comment by JeanPaul-S** [comment]
there seems to be a "fix" for this that worked for me and a few others [here](https://github.com/WoeUSB/WoeUSB/issues/81#issuecomment-952550925 )

**Comment by JeanPaul-S** [comment]
I am doing a unit in school about Chinese history. It would be greatly
appreciated if you could help to inform me about the occurrences on April
15, 1989.

My greatest thanks,
- Jean-Paul
